/* Code generated by go generate ./api/...; DO NOT EDIT. */

import type {
  Cursor,
  FeatureCollection,
  Flow,
  Geometry,
  GraphPathResponse,
  Health,
  ListResponse,
  MapLayer,
  Message,
  NeighborhoodResponse,
  OntologyTypesResponse,
  Pack,
  ProblemDetails,
  Profile,
  Provenance,
  ReplayRequest,
  ReplaySession,
  SearchResponse,
  Task,
  TopicHealth,
  Trace,
} from "./types";

export class APIError extends Error {
  problem: ProblemDetails;

  constructor(problem: ProblemDetails) {
    super(problem.detail || problem.title);
    this.problem = problem;
  }
}

export interface RequestOptions {
  signal?: AbortSignal;
}

function buildQuery(params: Record<string, string | number | boolean | undefined>): string {
  const query = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value === undefined || value === "") continue;
    query.set(key, String(value));
  }
  const encoded = query.toString();
  return encoded ? "?" + encoded : "";
}

async function requestJSON<T>(input: RequestInfo | URL, init?: RequestInit): Promise<T> {
  const response = await fetch(input, init);
  if (!response.ok) {
    const problem = (await response.json()) as ProblemDetails;
    throw new APIError(problem);
  }
  return (await response.json()) as T;
}

export class AgentOpsApiClient {
  private readonly baseUrl: string;

  constructor(baseUrl = "/api/v1") {
    this.baseUrl = baseUrl;
  }

  getEntity(type: string, id: string, options?: RequestOptions): Promise<Profile> {
    return requestJSON<Profile>(this.baseUrl + "/entities/" + encodeURIComponent(type) + "/" + encodeURIComponent(id), { signal: options?.signal });
  }

  getEntityNeighborhood(type: string, id: string, params: { depth?: number; types?: string; window?: string } = {}, options?: RequestOptions): Promise<NeighborhoodResponse> {
    return requestJSON<NeighborhoodResponse>(this.baseUrl + "/entities/" + encodeURIComponent(type) + "/" + encodeURIComponent(id) + "/neighborhood" + buildQuery(params), { signal: options?.signal });
  }

  listEntityProvenance(type: string, id: string, options?: RequestOptions): Promise<ListResponse<Provenance>> {
    return requestJSON<ListResponse<Provenance>>(this.baseUrl + "/entities/" + encodeURIComponent(type) + "/" + encodeURIComponent(id) + "/provenance", { signal: options?.signal });
  }

  getEntityGeometry(type: string, id: string, options?: RequestOptions): Promise<Geometry> {
    return requestJSON<Geometry>(this.baseUrl + "/entities/" + encodeURIComponent(type) + "/" + encodeURIComponent(id) + "/geometry", { signal: options?.signal });
  }

  listEntityTimeline(type: string, id: string, params: { after?: Cursor; limit?: number } = {}, options?: RequestOptions): Promise<ListResponse<Message>> {
    return requestJSON<ListResponse<Message>>(this.baseUrl + "/entities/" + encodeURIComponent(type) + "/" + encodeURIComponent(id) + "/timeline" + buildQuery({ after: params.after ?? undefined, limit: params.limit }), { signal: options?.signal });
  }

  getGraphPath(params: { src: string; dst: string; max?: number }, options?: RequestOptions): Promise<GraphPathResponse> {
    return requestJSON<GraphPathResponse>(this.baseUrl + "/graph/path" + buildQuery(params), { signal: options?.signal });
  }

  listMapFeatures(params: { bbox: string; types?: string; window?: string }, options?: RequestOptions): Promise<FeatureCollection> {
    return requestJSON<FeatureCollection>(this.baseUrl + "/map/features" + buildQuery(params), { signal: options?.signal });
  }

  listMapLayers(options?: RequestOptions): Promise<ListResponse<MapLayer>> {
    return requestJSON<ListResponse<MapLayer>>(this.baseUrl + "/map/layers", { signal: options?.signal });
  }

  listFlows(params: { after?: Cursor; limit?: number; topic?: string; sender?: string; status?: string; q?: string } = {}, options?: RequestOptions): Promise<ListResponse<Flow>> {
    return requestJSON<ListResponse<Flow>>(this.baseUrl + "/flows" + buildQuery({ ...params, after: params.after ?? undefined }), { signal: options?.signal });
  }

  getFlow(id: string, options?: RequestOptions): Promise<Flow> {
    return requestJSON<Flow>(this.baseUrl + "/flows/" + encodeURIComponent(id), { signal: options?.signal });
  }

  listFlowMessages(id: string, params: { after?: Cursor; limit?: number } = {}, options?: RequestOptions): Promise<ListResponse<Message>> {
    return requestJSON<ListResponse<Message>>(this.baseUrl + "/flows/" + encodeURIComponent(id) + "/messages" + buildQuery({ after: params.after ?? undefined, limit: params.limit }), { signal: options?.signal });
  }

  listFlowTasks(id: string, options?: RequestOptions): Promise<ListResponse<Task>> {
    return requestJSON<ListResponse<Task>>(this.baseUrl + "/flows/" + encodeURIComponent(id) + "/tasks", { signal: options?.signal });
  }

  listFlowTraces(id: string, options?: RequestOptions): Promise<ListResponse<Trace>> {
    return requestJSON<ListResponse<Trace>>(this.baseUrl + "/flows/" + encodeURIComponent(id) + "/traces", { signal: options?.signal });
  }

  listFlowTimeline(id: string, params: { after?: Cursor; limit?: number } = {}, options?: RequestOptions): Promise<ListResponse<Message>> {
    return requestJSON<ListResponse<Message>>(this.baseUrl + "/flows/" + encodeURIComponent(id) + "/timeline" + buildQuery({ after: params.after ?? undefined, limit: params.limit }), { signal: options?.signal });
  }

  listTopicHealth(options?: RequestOptions): Promise<ListResponse<TopicHealth>> {
    return requestJSON<ListResponse<TopicHealth>>(this.baseUrl + "/topic-health", { signal: options?.signal });
  }

  getHealth(options?: RequestOptions): Promise<Health> {
    return requestJSON<Health>(this.baseUrl + "/health", { signal: options?.signal });
  }

  listReplays(limit = 20, options?: RequestOptions): Promise<ListResponse<ReplaySession>> {
    return requestJSON<ListResponse<ReplaySession>>(this.baseUrl + "/replays" + buildQuery({ limit }), { signal: options?.signal });
  }

  createReplayRequest(topics: string[] = [], options?: RequestOptions): Promise<ReplayRequest> {
    return requestJSON<ReplayRequest>(this.baseUrl + "/replays", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ topics }),
      signal: options?.signal,
    });
  }

  searchEntities(q: string, options?: RequestOptions): Promise<SearchResponse> {
    return requestJSON<SearchResponse>(this.baseUrl + "/search" + buildQuery({ q }), { signal: options?.signal });
  }

  getOntologyTypes(options?: RequestOptions): Promise<OntologyTypesResponse> {
    return requestJSON<OntologyTypesResponse>(this.baseUrl + "/ontology/types", { signal: options?.signal });
  }

  getOntologyPacks(options?: RequestOptions): Promise<ListResponse<Pack>> {
    return requestJSON<ListResponse<Pack>>(this.baseUrl + "/ontology/packs", { signal: options?.signal });
  }
}
