/* Code generated by go generate ./api/...; DO NOT EDIT. */

export type Cursor = string | null;

export interface ProblemDetails {
  type: string;
  title: string;
  status: number;
  detail?: string;
  instance?: string;
}

export interface Entity {
  id: string;
  type: string;
  canonical_id: string;
  display_name?: string;
  first_seen: string;
  last_seen: string;
  attrs?: Record<string, unknown>;
}

export interface Edge {
  src_id: string;
  dst_id: string;
  type: string;
  valid_from: string;
  valid_to?: string;
  evidence_msg?: string;
  weight: number;
  attrs?: Record<string, unknown>;
}

export interface Provenance {
  subject_kind: string;
  subject_id: string;
  stage: string;
  policy_ver?: string;
  inputs?: Record<string, unknown>;
  decision?: string;
  reasons?: string[];
  produced_at: string;
}

export interface Geometry {
  entity_id: string;
  geometry_type: string;
  geojson: unknown;
  srid: number;
  min_lat: number;
  min_lon: number;
  max_lat: number;
  max_lon: number;
  z_min?: number;
  z_max?: number;
  observed_at: string;
  valid_to?: string;
}

export interface Neighbor {
  entity_id: string;
  entity_type: string;
  weight: number;
}

export interface Profile {
  entity: Entity;
  first_seen: string;
  last_seen: string;
  edge_counts: Record<string, number>;
  top_neighbors: Neighbor[];
}

export interface Pointer {
  bucket: string;
  key: string;
  size: number;
  sha256: string;
  content_type?: string;
  created_at?: string;
  proxy_id?: string;
  path: string;
}

export interface Message {
  id: string;
  topic: string;
  topic_family: string;
  partition: number;
  offset: number;
  timestamp: string;
  envelope_type?: string;
  sender_id?: string;
  correlation_id?: string;
  trace_id?: string;
  task_id?: string;
  parent_task_id?: string;
  status?: string;
  preview?: string;
  content?: string;
  lfs?: Pointer;
}

export interface Flow {
  id: string;
  topic_count: number;
  sender_count: number;
  topics: string[];
  senders: string[];
  trace_ids: string[];
  task_ids: string[];
  first_seen: string;
  last_seen: string;
  latest_status?: string;
  message_count: number;
  latest_preview?: string;
}

export interface TopicHealth {
  topic: string;
  messages_per_hour: number;
  message_density: string;
  active_agents: number;
  is_stale: boolean;
  last_message_at?: string;
}

export interface Health {
  connected: boolean;
  effective_topics: string[];
  group_id: string;
  accepted_count: number;
  rejected_count: number;
  mirrored_count: number;
  mirror_failed_count: number;
  rejected_by_reason: Record<string, number>;
  last_reject?: string;
  last_mirror_error?: string;
  last_poll_at?: string;
  replay_status?: string;
  replay_active: number;
  replay_last_error?: string;
  replay_last_finished_at?: string;
  replay_last_record_count: number;
  topic_health: TopicHealth[];
}

export interface ReplaySession {
  id: string;
  group_id: string;
  status: string;
  started_at: string;
  finished_at?: string;
  message_count: number;
  topics?: string[];
  last_error?: string;
}

export interface ReplayRequest {
  id: string;
  status: string;
  requested_at: string;
  topics: string[];
}

export interface TypeSpec {
  name: string;
  source: string;
}

export interface MapLayer {
  id: string;
  name: string;
  kind: string;
  url?: string;
  attribution?: string;
  source: string;
}

export interface Pack {
  name: string;
  version: string;
  description?: string;
  owner?: string;
  entity_types?: string[];
  edge_types?: string[];
  map_layers?: MapLayer[];
}

export interface Feature {
  type: "Feature";
  geometry: unknown;
  properties: Record<string, unknown>;
}

export interface FeatureCollection {
  type: "FeatureCollection";
  features: Feature[];
}

export interface ConsumerGroupMember {
  member_id: string;
  client_id: string;
  client_host: string;
  instance_id?: string;
}

export interface ConsumerGroup {
  group_id: string;
  state: string;
  protocol_type: string;
  protocol: string;
  members: ConsumerGroupMember[];
}

export interface OperatorState {
  supported: boolean;
  live_group_id?: string;
  replay_group_ids: string[];
  groups: ConsumerGroup[];
  last_error?: string;
}

export interface Trace {
  id: string;
  span_count: number;
  agents: string[];
  span_types: string[];
  latest_title?: string;
  started_at?: string;
  ended_at?: string;
  duration_ms?: number;
}

export interface Task {
  id: string;
  parent_task_id?: string;
  delegation_depth?: number;
  requester_id?: string;
  responder_id?: string;
  original_requester_id?: string;
  status?: string;
  description?: string;
  last_summary?: string;
  first_seen: string;
  last_seen: string;
}

export interface FusionMatch {
  alert_id: string;
  title: string;
  category: string;
  severity: string;
  source: string;
  canonical_url: string;
  match_reasons: string[];
}

export type AgentOpsMode = "OSINT" | "AGENTOPS" | "HYBRID";

export interface AgentOpsState {
  generated_at: string;
  enabled: boolean;
  ui_mode: AgentOpsMode;
  profile: string;
  group_name: string;
  topics: string[];
  flow_count: number;
  trace_count: number;
  task_count: number;
  message_count: number;
  health: Health;
  replay_sessions: ReplaySession[];
  flows: Flow[];
  traces: Trace[];
  tasks: Task[];
  messages: Message[];
}

export interface ListResponse<T> {
  items: T[];
  next: Cursor;
}

export interface GraphPathResponse {
  found: boolean;
  edges: Edge[];
}

export interface NeighborhoodResponse {
  entities: Entity[];
  edges: Edge[];
}

export interface OntologyTypesResponse {
  entity_types: TypeSpec[];
  edge_types: TypeSpec[];
}

export type SearchResult = Record<string, unknown>;
export type SearchResponse = ListResponse<SearchResult>;

export type AgentOpsPointer = Pointer;
export type AgentOpsMessage = Message;
export type AgentOpsFlow = Flow;
export type AgentOpsTrace = Trace;
export type AgentOpsTask = Task;
export type AgentOpsTopicHealth = TopicHealth;
export type AgentOpsHealth = Health;
export type AgentOpsReplaySession = ReplaySession;
export type AgentOpsConsumerGroupMember = ConsumerGroupMember;
export type AgentOpsConsumerGroup = ConsumerGroup;
export type AgentOpsOperatorState = OperatorState;
export type AgentOpsFusionMatch = FusionMatch;
