package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/scalytics/kafSIEM/internal/packs"
)

func main() {
	packsDir := flag.String("packs", "./packs", "Path to the active packs directory")
	outDir := flag.String("out", "docs/packs", "Directory for generated pack docs")
	flag.Parse()

	registry, err := packs.LoadDir(*packsDir)
	if err != nil {
		fail(err)
	}
	if err := os.MkdirAll(*outDir, 0o755); err != nil {
		fail(err)
	}
	for _, pack := range registry.Packs {
		body := renderPack(pack)
		path := filepath.Join(*outDir, pack.Name+".md")
		if err := os.WriteFile(path, body, 0o644); err != nil {
			fail(err)
		}
		fmt.Printf("wrote %s\n", path)
	}
}

func fail(err error) {
	_, _ = fmt.Fprintf(os.Stderr, "pack-docs: %v\n", err)
	os.Exit(1)
}

func renderPack(pack packs.Pack) []byte {
	var out bytes.Buffer
	title := packTitle(pack.Name)
	fmt.Fprintf(&out, "# %s Pack\n\n", title)
	fmt.Fprintln(&out, "<!-- Code generated by make pack-docs; DO NOT EDIT. -->")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "- **Name:** `%s`\n", pack.Name)
	fmt.Fprintf(&out, "- **Version:** `%s`\n", pack.Version)
	fmt.Fprintf(&out, "- **Schema:** `%s`\n", pack.SchemaVersion)
	if pack.Owner != "" {
		fmt.Fprintf(&out, "- **Owner:** `%s`\n", pack.Owner)
	}
	if pack.Requires.CoreMinVersion != "" {
		fmt.Fprintf(&out, "- **Core minimum version:** `%s`\n", pack.Requires.CoreMinVersion)
	}
	if pack.Description != "" {
		fmt.Fprintf(&out, "\n%s\n", pack.Description)
	}

	writeList(&out, "Entity Types", pack.EntityTypes)
	writeList(&out, "Edge Types", pack.EdgeTypes)
	writeMapLayers(&out, pack.MapLayers)
	writeDetectors(&out, pack.Detectors)
	writeViews(&out, pack.Views)
	writeQueries(&out, pack.Queries)
	writeList(&out, "Report Templates", pack.ReportTemplates)

	return out.Bytes()
}

func packTitle(name string) string {
	switch strings.ToLower(name) {
	case "scada":
		return "SCADA"
	case "drones":
		return "Drones"
	default:
		return strings.ToUpper(name[:1]) + name[1:]
	}
}

func writeList(out *bytes.Buffer, heading string, values []string) {
	fmt.Fprintf(out, "\n## %s\n\n", heading)
	if len(values) == 0 {
		fmt.Fprintln(out, "_None._")
		return
	}
	for _, value := range values {
		fmt.Fprintf(out, "- `%s`\n", value)
	}
}

func writeMapLayers(out *bytes.Buffer, layers []packs.MapLayer) {
	fmt.Fprintln(out, "\n## Map Layers")
	if len(layers) == 0 {
		fmt.Fprintln(out, "\n_None._")
		return
	}
	fmt.Fprintln(out, "\n| ID | Name | Kind | Entity Types | Render |")
	fmt.Fprintln(out, "| --- | --- | --- | --- | --- |")
	sort.Slice(layers, func(i, j int) bool { return layers[i].ID < layers[j].ID })
	for _, layer := range layers {
		fmt.Fprintf(out, "| `%s` | %s | `%s` | %s | %s |\n",
			layer.ID,
			escapeTable(layer.Name),
			layer.Kind,
			codeList(layer.EntityTypes),
			emptyOrCode(layer.Render),
		)
	}
}

func writeDetectors(out *bytes.Buffer, detectors []packs.Detector) {
	fmt.Fprintln(out, "\n## Detectors")
	if len(detectors) == 0 {
		fmt.Fprintln(out, "\n_None._")
		return
	}
	sort.Slice(detectors, func(i, j int) bool { return detectors[i].ID < detectors[j].ID })
	for _, detector := range detectors {
		fmt.Fprintf(out, "\n### `%s`\n\n", detector.ID)
		fmt.Fprintf(out, "- **Severity:** `%s`\n", detector.Severity)
		if detector.Window != "" {
			fmt.Fprintf(out, "- **Window:** `%s`\n", detector.Window)
		}
		if detector.ExplanationTemplate != "" {
			fmt.Fprintf(out, "- **Explanation:** %s\n", strings.TrimSpace(detector.ExplanationTemplate))
		}
		if len(detector.SuggestedActions) > 0 {
			fmt.Fprintln(out, "- **Suggested actions:**")
			for _, action := range detector.SuggestedActions {
				fmt.Fprintf(out, "  - %s\n", action)
			}
		}
		fmt.Fprintln(out, "\n```sql")
		fmt.Fprintln(out, strings.TrimSpace(detector.Query))
		fmt.Fprintln(out, "```")
	}
}

func writeViews(out *bytes.Buffer, views []packs.View) {
	fmt.Fprintln(out, "\n## Views")
	if len(views) == 0 {
		fmt.Fprintln(out, "\n_None._")
		return
	}
	sort.Slice(views, func(i, j int) bool { return views[i].ID < views[j].ID })
	for _, view := range views {
		fmt.Fprintf(out, "\n### `%s`\n\n", view.ID)
		fmt.Fprintf(out, "- **Entity type:** `%s`\n", view.EntityType)
		if view.Title != "" {
			fmt.Fprintf(out, "- **Title:** %s\n", view.Title)
		}
		if len(view.Fields) > 0 {
			fmt.Fprintln(out, "\n| Field | Label | Format | Hidden |")
			fmt.Fprintln(out, "| --- | --- | --- | --- |")
			for _, field := range view.Fields {
				fmt.Fprintf(out, "| `%s` | %s | %s | `%t` |\n",
					field.ID,
					escapeTable(field.Label),
					emptyOrCode(field.Format),
					field.Hidden,
				)
			}
		}
	}
}

func writeQueries(out *bytes.Buffer, queries []packs.QueryTemplate) {
	fmt.Fprintln(out, "\n## Query Templates")
	if len(queries) == 0 {
		fmt.Fprintln(out, "\n_None._")
		return
	}
	sort.Slice(queries, func(i, j int) bool { return queries[i].ID < queries[j].ID })
	for _, query := range queries {
		fmt.Fprintf(out, "\n### `%s`\n\n", query.ID)
		if query.Title != "" {
			fmt.Fprintf(out, "- **Title:** %s\n", query.Title)
		}
		if query.Description != "" {
			fmt.Fprintf(out, "- **Description:** %s\n", query.Description)
		}
		if len(query.Params) > 0 {
			fmt.Fprintln(out, "\n| Parameter | Type | Required | Description |")
			fmt.Fprintln(out, "| --- | --- | --- | --- |")
			for _, param := range query.Params {
				description := param.Description
				if description == "" {
					description = param.Label
				}
				fmt.Fprintf(out, "| `%s` | %s | `%t` | %s |\n",
					param.Name,
					emptyOrCode(param.Type),
					param.Required,
					escapeTable(description),
				)
			}
		}
		fmt.Fprintln(out, "\n```sql")
		fmt.Fprintln(out, strings.TrimSpace(query.SQL))
		fmt.Fprintln(out, "```")
	}
}

func codeList(values []string) string {
	if len(values) == 0 {
		return ""
	}
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, "`"+value+"`")
	}
	return strings.Join(quoted, ", ")
}

func emptyOrCode(value string) string {
	if value == "" {
		return ""
	}
	return "`" + value + "`"
}

func escapeTable(value string) string {
	return strings.ReplaceAll(value, "|", "\\|")
}
